[package]
name = "algorithms"
version = "0.0.1"
authors = ["Alex-Diez <alexvic.amatory@gmail.com>"]

[lib]
name = "algorithms"

[[test]]
name = "test"
path = "test/lib.rs"

[dependencies]
clippy = "0.0.41"
expectest = "0.4.1"
stainless = "0.1.4"
